snooze:
  fields:
    alarm_id:
      selector:
        text:
    entity_id:
      selector:
        entity:
          integration: daybreak
    minutes:
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: min
stop:
  fields:
    alarm_id:
      selector:
        text:
    entity_id:
      selector:
        entity:
          integration: daybreak
skip_next:
  fields:
    alarm_id:
      selector:
        text:
    entity_id:
      selector:
        entity:
          integration: daybreak
cancel_skip:
  fields:
    alarm_id:
      selector:
        text:
    entity_id:
      selector:
        entity:
          integration: daybreak
test:
  fields:
    alarm_id:
      selector:
        text:
    entity_id:
      selector:
        entity:
          integration: daybreak
    duration:
      default: 60
      selector:
        number:
          min: 10
          max: 1800
          unit_of_measurement: s
set_once:
  fields:
    alarm_id:
      selector:
        text:
    entity_id:
      selector:
        entity:
          integration: daybreak
    date:
      required: true
      selector:
        date:
    time:
      required: true
      selector:
        time:
    light_lead:
      selector:
        number:
          min: 0
          max: 240
          unit_of_measurement: min
clear_once:
  fields:
    alarm_id:
      selector:
        text:
    entity_id:
      selector:
        entity:
          integration: daybreak
