snooze:
  fields:
    alarm_id:
      selector:
        text:
    entity_id:
      selector:
        entity:
          integration: daybreak
    minutes:
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: min
stop:
  fields:
    alarm_id:
      selector:
        text:
    entity_id:
      selector:
        entity:
          integration: daybreak
skip_next:
  fields:
    alarm_id:
      selector:
        text:
    entity_id:
      selector:
        entity:
          integration: daybreak
cancel_skip:
  fields:
    alarm_id:
      selector:
        text:
    entity_id:
      selector:
        entity:
          integration: daybreak
test:
  fields:
    alarm_id:
      selector:
        text:
    entity_id:
      selector:
        entity:
          integration: daybreak
    duration:
      default: 60
      selector:
        number:
          min: 10
          max: 1800
          unit_of_measurement: s
